[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
libloading = "0.8.1"
notify = "6.1.1"

azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.9.0" }
tokio = { version = "1.36.0", features = ["full"] }
