[package]
name = "discord"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bichannel = { version = "0.0.4", features = ["crossbeam"] }
common = { path = "../../common" }
